### ISSUE TITLE
Pretrained model link is not found!

### ISSUE THREAD

**Issue by sithu31296** [leeyegy/SimDR#1]
Are you releasing pretrained models soon? Since the link is not working yet.

**Comment by leeyegy** [comment]
The pretrained models are going to be released within a week.

**Comment by sithu31296** [comment]
Oh! Glad to hear that! I'm waiting for it.

**Comment by katsura-jp** [comment]
Hi, @leeyegy 

How about this issue?
I am looking forward to the release.

Best,

**Comment by lichengxian** [comment]
非常期待SimDR的预训练模型，希望能尽快release，万分感谢！

**Comment by leeyegy** [comment]
The pre-trained models are released now. Sorry for the delay, I am so busy recently that I forget about this issue~
