### ISSUE TITLE
Questions about "adjust_target_weight"

### ISSUE THREAD

**Issue by yuzheyyyy** [leeyegy/SimDR#11]
https://github.com/leeyegy/SimDR/blob/30845b85a139a1ca88ee9f80e9e11b8ae677a7ec/lib/dataset/JointsDataset.py#L384
Should the if condition be "ul[0] >= (self.image_size[0])" rather than "ul[0] >= (self.image_size[0]*self.simdr_split_ratio)"? Since mu_x here is the value that is without multiplying with self.simdr_split_ratio.

**Comment by leeyegy** [comment]
Yes! Thanks for your pointing out.
