### ISSUE TITLE
heatmap后处理和多人姿态估计

### ISSUE THREAD

**Issue by zkdfbb** [leeyegy/SimDR#12]
想请教一下，你论文里面的heatmap后处理都用了哪些方式，在小输入尺寸下差别还蛮大的

SimDR这方法可以用在多人姿态估计里，想了一下one-stage的话貌似不太方便

**Comment by leeyegy** [comment]
The settings of heatmap-based methods discussed in our paper simply follow their original papers.
Which means, for HRNet&SimBa, shift strategy is adopted as post-processing; for TokenPose, DARK strategy is adopted as post-processing. By contrast, none of them is used by our proposed method (no need of extra post-processing for further performance improvement).

**Comment by leeyegy** [comment]
By far, SimDR works in top-down human pose estimation.
For bottom-up settings or else, we regard them as future work.
