### ISSUE TITLE
关键点得分

### ISSUE THREAD

**Issue by xuyun224** [leeyegy/SimDR#16]
最后得到的关键点置信度很低怎么办，都基本en小于0.5

**Comment by xuyun224** [comment]
> 

如果网络要求使用数据增强导致每次输入的图片大小都不相同，这种方式怎么使用simdr，可以给一点建议吗。

**Comment by xuyun224** [comment]
> 该方法的计算置信度的方式和基于heatmap的方案不一样，所以监督学出来的置信度会偏低，设置一个较低的阈值就可以了。 从我的角度，造成这种现象的主要原因可能是： heatmap的方案给的监督信号的最高激活点置信度是1，去掉了gauss分布的前面的系数项，所以整体学出来的置信度会偏高； 本方案的监督信号依照概率分布表达式给出（也就是最高激活点的概率会远小于1），所以也会造成模型训练完毕之后对应的关键点置信度的绝对值也会低

使用simdr的方法：1、如果网络要求使用了数据增强的方式导致每输入网络的图片大小

**Comment by xuyun224** [comment]
> 该方法的计算置信度的方式和基于heatmap的方案不一样，所以监督学出来的置信度会偏低，设置一个较低的阈值就可以了。 从我的角度，造成这种现象的主要原因可能是： heatmap的方案给的监督信号的最高激活点置信度是1，去掉了gauss分布的前面的系数项，所以整体学出来的置信度会偏高； 本方案的监督信号依照概率分布表达式给出（也就是最高激活点的概率会远小于1），所以也会造成模型训练完毕之后对应的关键点置信度的绝对值也会低

请问如果网络的输入使用了数据增强导致每次输入的大小都不相同，这种情况下怎么友好的使用simdr
       我在最后的固定大小的特征图上用simdr的方法，得到的结果并不理想

**Comment by leeyegy** [comment]
一个潜在的解决方案是：
按照**比例**来给监督信号的激活类别，例如，假定预先设计有1000个类别，那么在输入大小是100x100的坐标为1的对应的类别就应该是第10类；而在输入大小是500x500的坐标为1的对应的类别是第2类；

该思路仅供参考，作者们没有做过相关的实验验证～

**Comment by Blankit** [comment]
通过对输出取sigmoid，得到近似的概率值。
使用作者提供的模型，关键点的概率比较高，但是用自己的数据训练后，coco数据集的9、10即两个手腕上的点的概率比较低。
请问这是什么原因啊

**Comment by APeiZou** [comment]
> 最后得到的关键点置信度很低怎么办，都基本en小于0.5

Hello, 你好，我测试也发现置信度都很小都在0.2以下，有的0.1以下的？后来怎么解决呢？

**Comment by Boluo-XD** [comment]
> > 最后得到的关键点置信度很低怎么办，都基本en小于0.5
> 
> Hello, 你好，我测试也发现置信度都很小都在0.2以下，有的0.1以下的？后来怎么解决呢？

您好，我也有同样的疑惑，请问您解决了吗，感谢您的回复！

**Comment by DIANSLEE** [comment]
> > > 最后得到的关键点置信度很低怎么办，都基本en小于0.5
> > 
> > 
> > Hello, 你好，我测试也发现置信度都很小都在0.2以下，有的0.1以下的？后来怎么解决呢？
> 
> 您好，我也有同样的疑惑，请问您解决了吗，感谢您的回复！
您好我也是，请问解决了吗
