### ISSUE TITLE
IN_VIS_THRE configuration

### ISSUE THREAD

**Issue by Indigo6** [leeyegy/SimDR#17]
https://github.com/leeyegy/SimDR/blob/67216117f08d2ccfb65324859758aa007976831a/experiments/coco/hrnet/sa_simdr/w48_384x288_adam_lr1e-3_split1_5_sigma4.yaml#L117

Thank you for your great job! 
When evaluating, I found the 'IN_VIS_THRE' is set much smaller than those in the original HRNet cfgs, since the max activation of the 1D heatmap is really small after softmax. 
I wonder whether you can share **how to find the optimal 'IN_VIS_THRE' value?** I can't find it in the paper.
@leeyegy

**Comment by leeyegy** [comment]
It's an empirical value. Given the proposed method is different from heatmap-based pipeline, the settings need to be modified correspondingly.
