### ISSUE TITLE
代码中SimDR 和SA-SimDR区别

### ISSUE THREAD

**Issue by wanlipeng** [leeyegy/SimDR#19]
你好，我看代码中包含SimDR 和SA-SimDR两种不同配置，有啥区别呢

**Comment by leeyegy** [comment]
区别如下：
SimDR是one-hot（label smoothing）
SA-SimDR是使用了gaussian或者laplace进行smoothing
因此区别仅在于监督信号的概率分布

**Comment by wanlipeng** [comment]
感谢回复，刚看到代码也了解到了，所以作者实验使用SimDR和SA-SimDR这两个相比哪个效果会更好点呢，此外参数配置文件没找到LABEL_SMOOTHING这个参数值，实验使用的是0.1的吗？

**Comment by leeyegy** [comment]
在比较高的分辨率的情况下，gaussian label smoothing 会更好；在比较低的分辨率的情况，印象中两者差不多

**Comment by leeyegy** [comment]
one-hot的label smoothing的参数默认是0.1

**Comment by wanlipeng** [comment]
好的，多谢！！
