### ISSUE TITLE
你好  pose_resnet_upfree 是什么？它和pose_resnet有什么区别？

### ISSUE THREAD

**Issue by guzejungithub** [leeyegy/SimDR#25]

**Comment by leeyegy** [comment]
upfree去掉了所有的上采样层，可以提供更快的速度响应。
如果追求性能而不在意速度，建议使用pose_resnet
如果优先追求速度，建议使用pose_resnet_upfree
pose_resnet_upfree展示了：相对传统基于heatmap的方法，SimCC可以摆脱或者大大降低对于上采样层的严重依赖，即兼顾速度和性能

**Comment by leeyegy** [comment]
upfree去掉了所有的上采样层，可以提供更快的速度响应。
如果追求性能而不在意速度，建议使用pose_resnet
如果优先追求速度，建议使用pose_resnet_upfree
pose_resnet_upfree展示了：相对传统基于heatmap的方法，SimCC可以摆脱或者降低对于上采样层的严重依赖，即兼顾速度和性能

**Comment by guzejungithub** [comment]
再次非常感谢




谷泽军
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leeyegy/SimCC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月10日(星期二) 中午11:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [leeyegy/SimCC] 你好  pose_resnet_upfree 是什么？它和pose_resnet有什么区别？ (Issue #25)





 
upfree去掉了所有的上采样层，可以提供更快的速度响应。
 如果追求性能而不在意速度，建议使用pose_resnet
 如果优先追求速度，建议使用pose_resnet_upfree
 pose_resnet_upfree展示了：相对传统基于heatmap的方法，SimCC可以摆脱或者大大降低对于上采样层的严重依赖，即兼顾速度和性能
