### ISSUE TITLE
得到的置信度都小于0.1有什么办法改进吗

### ISSUE THREAD

**Issue by APeiZou** [leeyegy/SimDR#29]
@leeyegy  您好，得到的置信度都小于0.1有什么办法改进吗

**Comment by Boluo-XD** [comment]
您好我遇到了同样的问题，请问你解决了吗

**Comment by puyiwen** [comment]
> 您好我遇到了同样的问题，请问你解决了吗

你好，我用coco训练了之后在自己的数据集上进行测试，发现关键点的置信度都小于0.1，然后mAP为0，这个现象正常吗？在用RLE的时候就不会这样。。。
