### ISSUE TITLE
SimDR  head 不会带来GFLOP的增加吗？

### ISSUE THREAD

**Issue by APeiZou** [leeyegy/SimDR#5]
SimDR  head 不会带来GFLOP的增加吗？Decode部分的实现代码在哪啊？

**Comment by APeiZou** [comment]
@leeyegy

**Comment by leeyegy** [comment]
Q1："SimDR head 不会带来GFLOP的增加吗？"
A1： simdr head只是一层简单的分类器（线性层），GFLOPs基本不增加，参考论文中表格给出的数据（各个分辨率下测试结果都有）

Q2：“Decode部分的实现代码在哪啊？”
A2：lib/core/function.py，建议先仔细看下代码。。。
