### ISSUE TITLE
Multi-person detection

### ISSUE THREAD

**Issue by soans1994** [leeyegy/SimDR#7]
hello authors,

Sorry i want to ask a question related to Multi-person detection.
I want to ask wheter the COCO person dataset is specialized for multi-person?
i have trained a simple model using FCN for face keypoint regression. Can you please tell me how we can get heatmaps of muliple faces in the bottom-up approach. My current model takes input of 96x96x1 image and gives 96x96x15 size heatmaps for 15 keypoints. I trained my model using datset consisting of images with single face. Do i need the datset with multiple faces? and do I need bouding box information or mask information too?

Please give me your advice
thank you

**Comment by leeyegy** [comment]
Hi,

It seems that your question is less relevant to this repo. And I am not an expert in face landmark. Though, I can give you some information from the perspective of multi-person human pose estimation.

i) yes, you need to train your model using datasets with multi-person.
ii) in the bottom-up approaches, heatmaps are generated by multi-modal Gaussian Distribution. You can refer to https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation, which is a very famous and popular method for bottom-up Human Pose Estimation

**Comment by leeyegy** [comment]
Hope these may help~ 
Feel free to reopen this issue. Happy new year!

**Comment by soans1994** [comment]
@leeyegy 
Thank you very much. Yes I use gaussian filter to generate labels. My goal is to train multi face. Is it possible to convert single face dataset to multi by copying. And I believe I need bounding box information too when I have multiple faces? Previously I only use keypoints coordinate information

**Comment by leeyegy** [comment]
Copying or other data transforms is a potential solution but not good enough, because it may introduce gap.

**Comment by soans1994** [comment]
@leeyegy 

i took your advice, i tried multi-person dataset

Im using coco dataset now. I tried training images by cropping, but since it will be simila rto single face detection, i can only get single pose heatmap.

Next method im trying is consider the entire image, not cropped.  i hope the model learns to detect multi-person.

-my one training sample is as below.

for first person in the image: give the entire image (with multi-person) to the model (resized to 256x256), but only 1 label corresponding the the first person.
repeat procedure for all persons.

Does this work?

thank you
