### ISSUE TITLE
Poor performance with res50-simdr

### ISSUE THREAD

**Issue by SatMa34** [leeyegy/SimDR#8]
Hi, thanks for your brilliant work!
I have used provided yaml file to train SimBa-Res50-SimDR with input resolution set to 64*64, and the result is as follows:
![image](https://user-images.githubusercontent.com/19217861/149441156-a708a30e-5616-461f-8091-680bed0a6ee3.png)

The AP is only 35.4, much lower than 40.8 mentioned in the paper, did i miss something?

**Comment by SatMa34** [comment]
Probably because i didn't use the imagenet pretrained model, doing the experiment right now

**Comment by leeyegy** [comment]
Yes, the pretrained model helps improve the results, which is also widely-adopted by lots of work in this area(e.g., HRNet, SimpleBasline, etc.). You may have a try.
